export const Filters = [
  {
    label: 'All Questions',
    active: true,
  },
  {
    label: 'Most Upvoted',
  },
  {
    label: '#White Cloth',
  },
];

export const QandAs = [
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'low',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani is the founder of Tariqa Tijaaniyya',
    urgency: 'medium',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'medium',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'low',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'low',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani is the founder of Tariqa Tijaaniyya',
    urgency: 'medium',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'medium',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'low',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'low',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani is the founder of Tariqa Tijaaniyya',
    urgency: 'medium',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'medium',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'low',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'low',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani is the founder of Tariqa Tijaaniyya',
    urgency: 'medium',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'medium',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'low',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'low',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani is the founder of Tariqa Tijaaniyya',
    urgency: 'medium',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: '',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'medium',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'high',
    withVotes: true,
  },
  {
    question: 'Who is the founder of tariqa',
    answer: 'Sheikh Tijaani',
    urgency: 'low',
    withVotes: true,
  },
];
