import sheehu from "../../../assets/sheehu.JPG";
export const Shuyuukh = [
  {
    name: "Sheikh Umar Karkee",
    country: "Ghana",
    profile: sheehu,
    town: "Krachi",
  },
  {
    name: "Sheikh Abdullahi Gomda",
    country: "Ghana",
    profile: sheehu,
    town: "Yendi",
  },
  {
    name: "Sheikh AlHassan Salaga",
    country: "Ghana",
    profile: sheehu,
    town: "Salaga",
  },
  {
    name: "Sheikh Ahmad Muhammad Dan Tani",
    country: "Ghana",
    profile: sheehu,
    town: "Bawku",
  },
  {
    name: "Sheikh Abdullahi Ahmad Maikano",
    country: "Ghana",
    profile: sheehu,
    town: "Prang",
  },
  {
    name: "Sheikh Haroun Muhammad Al-Tijjani",
    country: "Ghana",
    profile: sheehu,
    town: "Kumasi",
  },

  {
    name: "Sheikh Baaban Makaranta ",
    country: "Ghana",
    profile: sheehu,
    town: "Kumasi",
  },
  {
    name: "Sheikh Baabal Waa'iz",
    country: "Ghana",
    profile: sheehu,
    town: "Kumasi",
  },
  {
    name: "Sheikh Liman Chiroma",
    country: "Ghana",
    profile: sheehu,
    town: "Kumasi",
  },
  {
    name: "Sheikh Garba Hakim",
    country: "Ghana",
    profile: sheehu,
    town: "Kumasi",
  },
  {
    name: "Sheikh Hassan Nasurudeen",
    country: "Ghana",
    profile: sheehu,
    town: "Kumasi",
  },
  {
    name: "Sheikh Usman Nuhu Sharubutu",
    country: "Ghana",
    profile: sheehu,
    town: "Accra",
  },

  {
    name: "Sheikh Muhammad Salis Shaban",
    country: "Ghana",
    profile: sheehu,
    town: "Accra",
  },
  {
    name: "Sheikh Kamaludeen Abubakar",
    country: "Ghana",
    profile: sheehu,
    town: "Accra",
  },
  {
    name: "Sheikh Wulugu Moore",
    country: "Ghana",
    profile: sheehu,
    town: "Bolgatanga",
  },
  {
    name: "Sheikh Jibril Sofo",
    country: "Ghana",
    profile: sheehu,
    town: "Bawku",
  },
  {
    name: "Sheikh Kakan Moore",
    country: "Ghana",
    profile: sheehu,
    town: "Bawku",
  },
  {
    name: "Sheikh Hamza Dan Gaata",
    country: "Ghana",
    profile: sheehu,
    town: "Tamale",
  },
  {
    name: "Sheikh Jamal Baaba",
    country: "Ghana",
    profile: sheehu,
    town: "Accra",
  },
  {
    name: "Sheikh Idris Sufii",
    country: "Ghana",
    profile: sheehu,
    town: "Accra",
  },
  {
    name: "Sheikh Sani Murtala",
    country: "Ghana",
    profile: sheehu,
    town: "Accra",
  },
  {
    name: "Sheikh Adam Kusuntu",
    country: "Ghana",
    profile: sheehu,
    town: "Accra",
  },
  {
    name: "Sheikh Yahyal Amin",
    country: "Ghana",
    profile: sheehu,
    town: "Accra",
  },
  {
    name: "Sheikh Zulkanain Askandar",
    country: "Ghana",
    profile: sheehu,
    town: "Salaga",
  },
  {
    name: "Sheikh Muhdi Salga",
    country: "Nigeria",
    profile: sheehu,
    town: "Kano",
  },
  {
    name: "Sheikh Malam Mijiyawa",
    country: "Nigeria",
    profile: sheehu,
    town: "Kano",
  },
  {
    name: "Sheikh Mahmud Gibrima",
    country: "Nigeria",
    profile: sheehu,
    town: "Guru",
  },
  {
    name: "Sheikh Ahmed Tijjani Usman",
    country: "Nigeria",
    profile: sheehu,
    town: "Kano",
  },
  {
    name: "Sheikh Atiku Sanka",
    country: "Nigeria",
    profile: sheehu,
    town: "Kano",
  },
  {
    name: "Sheikh Sani Kafanga",
    country: "Nigeria",
    profile: sheehu,
    town: "Kano",
  },
  {
    name: "Sheikh Mai Hula",
    country: "Nigeria",
    profile: sheehu,
    town: "Kano",
  },
  {
    name: "Sheikh Aliyu Harazimi",
    country: "Nigeria",
    profile: sheehu,
    town: "Kano",
  },
  {
    name: "Sheikh Abul Fathi",
    country: "Nigeria",
    profile: sheehu,
    town: "Maiduguri",
  },
  {
    name: "Sheikh Adam Dan Kilori",
    country: "Nigeria",
    profile: sheehu,
    town: "Maiduguri",
  },
  {
    name: "Sheikh Almiskin",
    country: "Nigeria",
    profile: sheehu,
    town: "Maiduguri",
  },
  {
    name: "Sheikh Tahiru Bauchi",
    country: "Nigeria",
    profile: sheehu,
    town: "Bauchi",
  },
  {
    name: "Sheikh Jamiu Bulala",
    country: "Nigeria",
    profile: sheehu,
    town: "Ofa",
  },
  {
    name: "Sheikh Yahuza Zaria",
    country: "Nigeria",
    profile: sheehu,
    town: "Zaria",
  },
  {
    name: "Sheikh Abdul Qadir Zaria",
    country: "Nigeria",
    profile: sheehu,
    town: "Zaria",
  },
  {
    name: "Sheikh Sheriff Ibrahim Swallah",
    country: "Nigeria",
    profile: sheehu,
    town: "Maiduguri",
  },
  {
    name: "Alhaji Abdullahi Nyass",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
  {
    name: "Sheikh Alhaji Ibrahim Nyass",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
  {
    name: "Sheikh Muhammad Khalifa",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
  {
    name: "Sheikh Abubakar Sirrin Baye",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
  {
    name: "Sheikh Aliyu Cissey",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
  {
    name: "Khalifa Abdullahi Nyass",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
  {
    name: "Khalifa Ahmed Tijjani Nyass",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
  {
    name: "Khalifa Mahy Nyass",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
  {
    name: "heikh Hassan Cissey",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
  {
    name: "sheikh Ahmed Tijjani Cissey",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
  {
    name: "Sheikh Muhammed Amin Nyass",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },

  {
    name: "Sheikh Muhammad Nazir Nyass",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
  {
    name: "Sheikh Kabir Faye",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
  {
    name: "Sheikh Muhammad Nyang",
    country: "Senegal",
    profile: sheehu,
    town: "Kaolack",
  },
];
